name: Upload to PyPI
on:
  push:
    tags:
      - "*"

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6

      - uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.x

      - run: pip install build

      - run: python -m build --wheel --sdist

      - run: pip install twine

      - run: twine upload --skip-existing dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
